#! /bin/bash

sudo apt-get update
sudo apt-get install libx11-dev build-essential riscv64-unknown-elf-gcc python3

wget https://ftp.gnu.org/gnu/lightning/lightning-2.2.3.tar.gz
tar -xf lightning-2.2.3.tar.gz
rm lightning-2.2.3.tar.gz
pushd lightning-2.2.3
./configure
sudo make install
popd
sudo rm -rf ./lightning-2.2.3

python3 -m venv .venv
source .venv/bin/activate
pip install -r RISC-BF/requirements.txt
